on: push

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install pytest pytest-describe pytest-spec pytest-mock

      - name: Run unit tests
        run: pytest --spec test_bute.py

  functional-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@master

      - name: Install Behave
        run: |
          pip install behave behave-webdriver

      - name: Run functional tests
        run: behave
